language: php

php:
  - hhvm

env:
  global:
    - KEY_SERVER="hkp://keyserver.ubuntu.com:80"
    - MONGO_REPO_URI="http://repo.mongodb.com/apt/ubuntu"
    - MONGO_REPO_TYPE="precise/mongodb-enterprise/"
    - SOURCES_LOC="/etc/apt/sources.list.d/mongodb.list"
    - HHVM_BUCKET="https://s3.amazonaws.com/drivers.mongodb.org/hhvm"
  matrix:
    - SERVER_VERSION=2.4 PECL_VERSION=beta
    - SERVER_VERSION=2.6 PECL_VERSION=beta
    - SERVER_VERSION=3.0 PECL_VERSION=beta
    - SERVER_VERSION=2.4 HHVM_VERSION=hhvm-mongodb-1.0alpha1.tgz
    - SERVER_VERSION=2.6 HHVM_VERSION=hhvm-mongodb-1.0alpha1.tgz
    - SERVER_VERSION=3.0 HHVM_VERSION=hhvm-mongodb-1.0alpha1.tgz

matrix:
  exclude:
    - php: 5.4
      env: SERVER_VERSION=2.4 HHVM_VERSION=hhvm-mongodb-1.0alpha1.tgz
    - php: 5.4
      env: SERVER_VERSION=2.6 HHVM_VERSION=hhvm-mongodb-1.0alpha1.tgz
    - php: 5.4
      env: SERVER_VERSION=3.0 HHVM_VERSION=hhvm-mongodb-1.0alpha1.tgz
    - php: 5.5
      env: SERVER_VERSION=2.4 HHVM_VERSION=hhvm-mongodb-1.0alpha1.tgz
    - php: 5.5
      env: SERVER_VERSION=2.6 HHVM_VERSION=hhvm-mongodb-1.0alpha1.tgz
    - php: 5.5
      env: SERVER_VERSION=3.0 HHVM_VERSION=hhvm-mongodb-1.0alpha1.tgz
    - php: 5.6
      env: SERVER_VERSION=2.4 HHVM_VERSION=hhvm-mongodb-1.0alpha1.tgz
    - php: 5.6
      env: SERVER_VERSION=2.6 HHVM_VERSION=hhvm-mongodb-1.0alpha1.tgz
    - php: 5.6
      env: SERVER_VERSION=3.0 HHVM_VERSION=hhvm-mongodb-1.0alpha1.tgz
    - php: hhvm
      env: SERVER_VERSION=2.4 PECL_VERSION=beta
    - php: hhvm
      env: SERVER_VERSION=2.6 PECL_VERSION=beta
    - php: hhvm
      env: SERVER_VERSION=3.0 PECL_VERSION=beta

before_install:
  - sudo apt-key adv --keyserver ${KEY_SERVER} --recv 7F0CEB10
  - echo "deb ${MONGO_REPO_URI} ${MONGO_REPO_TYPE}${SERVER_VERSION} multiverse" | sudo tee ${SOURCES_LOC}
  - sudo apt-get update -qq

install:
  - if dpkg --compare-versions ${SERVER_VERSION} le "2.4"; then export SERVER_PACKAGE=mongodb-10gen-enterprise; else export SERVER_PACKAGE=mongodb-enterprise; fi
  - sudo apt-get install ${SERVER_PACKAGE} -y
  - sudo apt-get install gdb -y
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then pecl install -f mongodb-${PECL_VERSION}; fi;
  - if [[ "$TRAVIS_PHP_VERSION" = "hhvm" ]]; then .travis/build_hhvm.sh ${HHVM_BUCKET}/${HHVM_VERSION}; fi;

before_script:
  - if dpkg --compare-versions ${SERVER_VERSION} le "2.4"; then export SERVER_SERVICE=mongodb; else export SERVER_SERVICE=mongod; fi
  - if ! nc -z localhost 27017; then sudo service ${SERVER_SERVICE} start; fi
  - mongod --version
  - php -r 'echo phpversion("mongodb");'
  - composer install --no-interaction --prefer-source
  - ulimit -c
  - ulimit -c unlimited -S

script:
  - phpunit --debug || RESULT=$?
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb `php -r 'echo PHP_BINARY;'` core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;
  - if [[ ${RESULT} != 0 ]]; then exit $RESULT ; fi;
