language: php
dist: trusty
sudo: false 

services:
  - mongodb

addons:
  apt:
    packages: &common_packages
      - gdb

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: &common_env DRIVER_VERSION=1.3.0RC1 SERVER_VERSION=3.4
      addons: &common_addons
        apt: 
          sources: [ mongodb-3.4-precise ]
          packages: [ mongodb-org=3.4.9, *common_packages ]
    - php: 5.6
      env: *common_env
      addons: *common_addons
    - php: 7.0
      env: *common_env
      addons: *common_addons
    - php: 7.1
      env: *common_env
      addons: *common_addons
    - php: 7.2
      env: *common_env
      addons: *common_addons
    - php: 7.0
      env: DRIVER_VERSION=1.3.0RC1 SERVER_VERSION=2.4
      addons:
        apt:
          sources: [ mongodb-upstart ]
          packages: [ mongodb-10gen=2.4.14, *common_packages ]
    - php: 7.0
      env: DRIVER_VERSION=1.3.0RC1 SERVER_VERSION=2.6
      addons:
        apt:
          sources: [ mongodb-upstart ]
          packages: [ mongodb-org=2.6.12, *common_packages ]
    - php: 7.0
      env: DRIVER_VERSION=1.3.0RC1 SERVER_VERSION=3.0
      addons:
        apt:
          sources: [ mongodb-3.0-precise ]
          packages: [ mongodb-org=3.0.15, *common_packages ]
    - php: 7.0
      env: DRIVER_VERSION=1.3.0RC1 SERVER_VERSION=3.2
      addons:
        apt:
          sources: [ mongodb-3.2-precise ]
          packages: [ mongodb-org=3.2.16, *common_packages ]
    - php: 7.0
      env: DRIVER_VERSION=devel SERVER_VERSION=3.4
      addons: *common_addons

before_install:
  - pip install "mongo-orchestration>=0.6.7,<1.0" --user `whoami`
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${SERVER_VERSION}.tgz
  - tar zxf mongodb-linux-x86_64-${SERVER_VERSION}.tgz
  - export PATH=${PWD}/mongodb-linux-x86_64-${SERVER_VERSION}/bin/:${PATH}
  - mongod --version

before_script:
  - mongo-orchestration start
  - pecl install -f mongodb-${DRIVER_VERSION}
  - php --ri mongodb
  - composer install --dev --no-interaction --prefer-source
  - ulimit -c
  - ulimit -c unlimited -S

script:
  - vendor/bin/phpunit --debug

after_failure:
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb `php -r 'echo PHP_BINARY;'` core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;

after_script:
  - mongo-orchestration stop
